### ISSUE TITLE
Thank you for including our paper and a small request for clarification

### ISSUE THREAD

**Issue by keikeiqi** [tim-learn/awesome-test-time-adaptation#9]
Hi!
I am very happy to see our paper "[Zeng et al., Proc. ACMMM 2023] Exploring motion cues for video test-time adaptation" included under TTA-OTTA.md. Thank you so much for adding it!
I noticed that our paper is currently categorized under "Misc" and that the method's abbreviation is missing. Our paper focuses on TTA in the video domain, so I would kindly request that it be reclassified under the "video" category. Additionally, it would be great if the acronym "AME" could be added before the title.
Thank you again for your work!
Best regards,
Qi Deng

**Comment by tim-learn** [comment]
Hi, Qi!

We have created a new tag for 'Action Recognition' and have moved your paper under this category. Thank you for your reminder!

Best regards

**Comment by tim-learn** [comment]
> Hi! I am very happy to see our paper "[Zeng et al., Proc. ACMMM 2023] Exploring motion cues for video test-time adaptation" included under TTA-OTTA.md. Thank you so much for adding it! I noticed that our paper is currently categorized under "Misc" and that the method's abbreviation is missing. Our paper focuses on TTA in the video domain, so I would kindly request that it be reclassified under the "video" category. Additionally, it would be great if the acronym "AME" could be added before the title. Thank you again for your work! Best regards, Qi Deng

Hi, Qi!

We have created a new tag for 'Action Recognition' and have moved your paper under this category. Thank you for your reminder!

Best regards
